name: Test and Deploy

on:
  push:
    branches:
      - "main"
  pull_request:

env:
  DOCKER_USERNAME: tobiaszimmer

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "temurin"
          cache: maven

      - name: Run tests
        run: |
          cd ufoproject
          mvn verify

      - name: deploy to dockerhub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
          docker build --tag "$DOCKER_USERNAME/research-project:latest" .
          docker push "$DOCKER_USERNAME/research-project:latest"
